# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    outputs:
      sha: ${{ steps.shastep.outputs.sha }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: ls
        run: ls ${{ github.workspace }}

      - id: shastep
        name: set sha output
        run: | 
            SHA=$(shasum -a 256 ${{ github.workspace }}/Casks/conduktor.rb | head -c 64)
            echo "::set-output name=sha::$SHA"
   
      - name: get output
        run: echo "SHA256 is ${{ steps.shastep.outputs.sha }}."
        
        
      - name: update the conductor tap
        run: |
            git clone git@github.com:golopupinsky/homebrew-tmp.git
            cd homebrew-tmp/Casks/
            awk -i inplace 'NR==2{print "  version \"2.16\""; next}1' conduktor.rb
            awk -i inplace 'NR==3{print "  sha256 \"${{ steps.shastep.outputs.sha }}\""; next}1' conduktor.rb
            git add conduktor.rb
            git push

            

